"use client";

/**
 * CoachCard — top block of Page B.
 *
 * Shows "今天 Duffy 想跟你說" — a 1-3 sentence message generated by
 * /api/coach. Cached 1h server-side; user can force refresh.
 */

import { useCallback, useEffect, useState } from "react";
import { motion } from "motion/react";
import { tokenFetch } from "@/lib/security/sidecar-token";

type CoachCardData = {
  message: string;
  generated_at: number;
  has_high_unread: boolean;
  high_unread_count: number;
  used: {
    silhouette_version: number | null;
    summary_week: string | null;
    observations_count: number;
  };
};

type State =
  | { kind: "loading" }
  | { kind: "loaded"; card: CoachCardData; stale: boolean }
  | { kind: "error"; message: string };

const LOCAL_KEY = "yen-hub:coach-card";

/** SWR-style client cache. localStorage is per-origin (so it resets on
 *  port change), but within a session it eliminates the "loading…" flash
 *  on every page mount. Server-side persistent cache handles the cross-
 *  port case so the network roundtrip is still fast. */
function readLocal(): CoachCardData | null {
  try {
    const raw = localStorage.getItem(LOCAL_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw) as CoachCardData;
    if (!parsed || typeof parsed.message !== "string") return null;
    return parsed;
  } catch {
    return null;
  }
}

function writeLocal(c: CoachCardData): void {
  try {
    localStorage.setItem(LOCAL_KEY, JSON.stringify(c));
  } catch {
    /* quota / private browsing — silent */
  }
}

type Props = {
  /** Slice 8.12 — server-rendered initial card (from generateCoachCard).
   *  When present, no "loading…" flash on first paint, even fresh sessions. */
  initial?: CoachCardData | null;
};

export function CoachCard({ initial }: Props = {}) {
  // Initial-state priority: server prop > localStorage > "loading".
  // Server prop wins because it bypasses the per-port localStorage limit
  // (localStorage is wiped every .app restart because the port changes).
  const [state, setState] = useState<State>(() => {
    if (initial) return { kind: "loaded", card: initial, stale: false };
    if (typeof window === "undefined") return { kind: "loading" };
    const local = readLocal();
    return local
      ? { kind: "loaded", card: local, stale: true }
      : { kind: "loading" };
  });
  // Persist server-supplied initial to localStorage so within-session
  // navigations (Page A → Page B → A → B) keep being instant.
  useEffect(() => {
    if (initial) writeLocal(initial);
  }, [initial]);
  const [refreshing, setRefreshing] = useState(false);

  const load = useCallback(async (refresh: boolean) => {
    try {
      const res = await tokenFetch(
        refresh ? "/api/coach?refresh=1" : "/api/coach",
      );
      if (!res.ok) {
        const j = (await res.json()) as { error?: string };
        setState((prev) =>
          prev.kind === "loaded"
            ? prev // keep showing the stale card if revalidate fails
            : { kind: "error", message: j.error ?? `HTTP ${res.status}` },
        );
        return;
      }
      const data = (await res.json()) as { card: CoachCardData };
      writeLocal(data.card);
      setState({ kind: "loaded", card: data.card, stale: false });
    } catch (e) {
      setState((prev) =>
        prev.kind === "loaded"
          ? prev
          : {
              kind: "error",
              message: e instanceof Error ? e.message : String(e),
            },
      );
    }
  }, []);

  // Always revalidate on mount. If TTL hasn't expired, the server returns
  // its cached copy fast — but we still benefit from sync between tabs.
  useEffect(() => {
    void load(false);
  }, [load]);

  const refresh = async () => {
    setRefreshing(true);
    await load(true);
    setRefreshing(false);
  };

  const accent = "var(--accent)";

  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.45, ease: "easeOut" }}
      className="rounded-2xl p-6 pointer-events-auto"
      style={{
        background: "rgba(255,255,255,0.04)",
        border: `1px solid ${accent}`,
        boxShadow: "0 1px 0 rgba(255,255,255,0.04) inset",
      }}
    >
      <div className="flex items-center justify-between mb-3">
        <div className="text-[10px] font-mono tracking-[0.32em] uppercase text-[var(--warn)]">
          今天 Duffy 想跟你說
        </div>
        <button
          type="button"
          onClick={refresh}
          disabled={refreshing}
          className="text-[10px] font-mono tracking-[0.18em] uppercase text-[var(--fg-3)] hover:text-[var(--fg-1)] transition-colors disabled:opacity-40"
        >
          {refreshing ? "refreshing…" : "↻ refresh"}
        </button>
      </div>

      {state.kind === "loading" && (
        <div className="text-[14px] text-[var(--fg-3)]">loading…</div>
      )}
      {state.kind === "error" && (
        <div className="text-[12px] text-[var(--danger)]">
          coach error: {state.message}
        </div>
      )}
      {state.kind === "loaded" && (
        <>
          <div className="text-[18px] leading-relaxed text-[var(--fg-0)] whitespace-pre-wrap">
            {state.card.message}
          </div>
          <div className="mt-4 flex gap-3 text-[10px] font-mono tracking-[0.18em] uppercase text-[var(--fg-3)]">
            {state.card.high_unread_count > 0 && (
              <span style={{ color: "var(--warn)" }}>
                {state.card.high_unread_count} HIGH unread
              </span>
            )}
            <span>
              gen {new Date(state.card.generated_at).toLocaleTimeString("zh-TW")}
            </span>
            {state.card.used.silhouette_version != null && (
              <span>silhouette v{state.card.used.silhouette_version}</span>
            )}
            {state.card.used.summary_week && (
              <span>{state.card.used.summary_week}</span>
            )}
          </div>
        </>
      )}
    </motion.div>
  );
}
