/**
 * Duffy — Yen's main agent.
 *
 * Slice 6 / Duffy v0: tools + intent approval.
 * Slice 7A: + frozen system prompt with silhouette + current week summary
 * injected once at session start (Hermes pattern). This preserves the LLM
 * prefix cache while giving Duffy persistent context.
 * Slice 7.5: SOUL.md vault-loaded personality (`06 - AI Data/agents/duffy.md`).
 * Slice 7.7: inflight store — keep streamText running even when Yen closes
 * the palette mid-thought; client merges back on reconnect.
 *
 * If no LLM key is configured, returns a 500 JSON instead of pretending to
 * work.
 */

import { NextResponse } from "next/server";
import {
  convertToModelMessages,
  smoothStream,
  stepCountIs,
  streamText,
  type UIMessage,
} from "ai";
import { duffyTools } from "@/lib/agent/duffy/tools";
import { DUFFY_OPERATIONAL_RULES } from "@/lib/agent/duffy/prompt";
import { loadDuffySoul } from "@/lib/agent/agents/duffy-soul";
import {
  appendInflight,
  finalizeInflight,
  startInflight,
} from "@/lib/agent/duffy/inflight-store";
import {
  getCurrentSilhouette,
  renderSilhouetteForPrompt,
} from "@/lib/agent/storage/silhouettes";
import {
  getCurrentWeekSummary,
  renderSummaryForPrompt,
} from "@/lib/agent/storage/summaries";
import { hasAnyLLMKey, pickModel, modelLabel } from "@/lib/ai/model";
import { recordRuntime } from "@/lib/agent/duffy/flight-recorder";

export type DuffyContext = {
  /** Yen's request, with the leading "Duffy" stripped. */
  prompt: string;
  /** Full chat history (UI messages). The leading name is still present in
   * the last user message — that's fine; the model sees it as part of the
   * normal flow. */
  messages: UIMessage[];
  /** Conversation id from the client. When present, runDuffy maintains an
   * inflight entry so that closing the palette doesn't lose the response.
   * Omit for non-conversational invocations (cron, bootstrap, etc.). */
  conversationId?: string;
};

/**
 * Compose the frozen system prompt for a session: identity rules + current
 * silhouette + current week summary. Pre-bootstrap (no silhouette yet) gets
 * an inline note instead, so Duffy knows to offer "introduce yourself".
 */
async function composeSystemPrompt(): Promise<string> {
  // 5-part composition (Hermes-style frozen injection):
  //   0. TIME    — current instant (server-injected, AI never has to fetch)
  //   1. SOUL    — who Duffy is (vault-editable, personality)
  //   2. RULES   — operational protocol (in code, engineering)
  //   3. SILHOUETTE — Duffy's portrait of Yen (Slice 7A)
  //   4. SUMMARY — current week snapshot (Slice 7A)
  //
  // 2026-06-13 — added TIME injection after the «5 分鐘後 → 5 小時後» incident.
  // Kimi reliably refuses to call get_current_time. Solution per the principle
  // «已知事實不該外包給 AI 自取»: server embeds time, AI just reads. The tool
  // stays available for finer queries (ISO week, weekday_num) but isn't needed
  // for the common case.
  const [soul, sil, sum] = await Promise.all([
    loadDuffySoul(),
    getCurrentSilhouette(),
    getCurrentWeekSummary(),
  ]);
  const parts: string[] = [];

  // 0. TIME — frozen as of this prompt build.
  const now = new Date();
  const tpe = now.toLocaleString("zh-TW", {
    timeZone: "Asia/Taipei",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false,
    weekday: "long",
  });
  const tpeDate = now
    .toLocaleString("sv-SE", { timeZone: "Asia/Taipei" })
    .slice(0, 10);
  parts.push(
    `# ⏰ AUTHORITATIVE TIME — TRUST THIS, NOT TOOL/SCHEDULE RETURNS\n\n` +
      `The block below is generated by the SERVER (Node.js \`new Date()\`) at the moment this prompt was built. It is fresh THIS turn. It is NOT a tool return value — different category, different reliability.\n\n` +
      `**Past time errors (e.g. schedule \`next_fire\` / \`not_before_iso\` being years off) came from STALE SCHEDULE DATA, not from this block. Do not confuse the two. This block has the operating system clock — those don't.**\n\n` +
      `[現在時間] ${tpe} (Asia/Taipei)\n` +
      `[今天日期] ${tpeDate}\n` +
      `[ISO UTC] ${now.toISOString()}\n` +
      `[epoch_ms] ${now.getTime()}\n\n` +
      `Rules:\n` +
      `- ❌ NEVER ask Yen «今天是幾月幾號» / «現在幾點» — the answer is in [今天日期] / [現在時間] above.\n` +
      `- ❌ NEVER say «我無法確定時間» or «所有系統時間都不可信» — that's wrong; this block is authoritative.\n` +
      `- ❌ NEVER call \`get_current_time\` just to learn the date or current time — it's already here.\n` +
      `- ✅ For relative scheduling: use the structured \`not_before_relative\` / \`recurrence\` fields on \`propose_schedule\` — server reads [epoch_ms] for you.\n` +
      `- ✅ Call \`get_current_time\` only for refinement fields not in the block above: ISO week-of-year, weekday_num for cron, sub-second precision.\n\n---\n\n`,
  );

  // 1. SOUL — Yen's writing about Duffy.
  parts.push(
    "# Who you are (SOUL — edited by Yen in `06 - AI Data/agents/duffy.md`)\n\n",
  );
  parts.push(soul);
  // 2. Operational rules.
  parts.push("\n\n---\n\n");
  parts.push(DUFFY_OPERATIONAL_RULES);
  // 3. Silhouette.
  if (sil) {
    parts.push("\n\n---\n\n" + renderSilhouetteForPrompt(sil));
  } else {
    parts.push(
      '\n\n---\n\n# Silhouette of Yen\n\n_(not yet bootstrapped — propose_silhouette_update with field="full" if Yen asks you to introduce yourself or once enough observations have accumulated)_',
    );
  }
  // 4. Current week summary.
  if (sum) {
    parts.push("\n\n---\n\n" + renderSummaryForPrompt(sum));
  } else {
    parts.push(
      "\n\n---\n\n# Current week summary\n\n_(no summary for this week yet — Sunday cron will propose one)_",
    );
  }
  return parts.join("");
}

const GREET_INIT_SENTINEL = "__DUFFY_GREET_INIT__";

/** Client emits this sentinel as a hidden user message right after the
 *  new-conversation animation finishes. Replace it server-side with a
 *  clear instruction so Kimi (which is less reliable than Claude at following
 *  subtle prompt rules) reliably produces a greeting. */
function rewriteGreetSentinel(messages: UIMessage[]): UIMessage[] {
  if (messages.length === 0) return messages;
  const last = messages[messages.length - 1];
  if (last.role !== "user") return messages;
  const text = (last.parts ?? [])
    .filter((p): p is { type: "text"; text: string } => p.type === "text")
    .map((p) => p.text)
    .join("")
    .trim();
  if (text !== GREET_INIT_SENTINEL) return messages;
  const rewritten: UIMessage = {
    ...last,
    parts: [
      {
        type: "text",
        text:
          "(系統訊息: Yen 剛打開一個全新對話。請以你 SOUL 中的語氣,用 ONE 短句主動向他打招呼。不要說「您好」、不要 emoji、不要列點、不要呼叫任何工具、不要包含任何 sentinel。)",
      },
    ],
  };
  return [...messages.slice(0, -1), rewritten];
}

export async function runDuffy(ctx: DuffyContext): Promise<Response> {
  if (!hasAnyLLMKey()) {
    return NextResponse.json(
      {
        error:
          "duffy needs an llm key — set KIMI_API_KEY or ANTHROPIC_API_KEY in the env, then restart dev/app.",
      },
      { status: 500 },
    );
  }

  // Slice 7.7+: detect the hidden greet sentinel and rewrite it to a clear
  // instruction. More reliable than depending on the LLM to follow a subtle
  // prompt rule, especially on Kimi K2.6.
  const messages = rewriteGreetSentinel(ctx.messages);

  const systemPrompt = await composeSystemPrompt();

  // Per-turn ID. Used as the inflight key tail; client matches via
  // conversation_id but turnId helps debug "which response is this".
  const turnId = `turn_${Date.now().toString(36)}_${Math.random()
    .toString(36)
    .slice(2, 8)}`;

  // Single-line console marker. Tail this when something looks wrong.
  console.log(
    `[duffy] provider=${process.env.DUFFY_PROVIDER ?? "(auto)"} ` +
      `model=${process.env.DUFFY_MODEL ?? "(default)"} ` +
      `kimi=${process.env.KIMI_API_KEY ? "yes" : "no"} ` +
      `anthropic=${process.env.ANTHROPIC_API_KEY ? "yes" : "no"} ` +
      `prompt_chars=${systemPrompt.length} ` +
      `convo=${ctx.conversationId ?? "(none)"} ` +
      `turn=${turnId}`,
  );

  // Flight recorder — write Duffy's actual prompt + tool calls + response
  // into Glasshouse's events tape. See lib/agent/duffy/flight-recorder.ts.
  recordRuntime("prompt-built", {
    turnId,
    convoId: ctx.conversationId ?? null,
    chars: systemPrompt.length,
    firstChars: systemPrompt.slice(0, 800),
    lastUserMessage: messages.length
      ? (messages[messages.length - 1].parts ?? [])
          .filter(
            (p): p is { type: "text"; text: string } => p.type === "text",
          )
          .map((p) => p.text)
          .join("")
          .slice(0, 300)
      : null,
  });

  const convoId = ctx.conversationId;
  if (convoId) {
    await startInflight({ conversationId: convoId, turnId });
  }

  // Patch A (2026-06-14) — turn finalize 守門員。
  //
  // 舊版只靠 streamText 的 onFinish 收尾；若 SDK 跟 Kimi 對 finish_reason:
  // "tool_calls" 之後的後續期待不一致（SDK 等下一 step、Kimi 不送）、onFinish
  // 永不觸發、inflight 永遠 status: "streaming"。今晚 turn_mqczoqc8_4c3bwy 就
  // 是這個 — 磁帶有 prompt-built + tool-call + tool-result 但無 response-finished。
  //
  // 結構性修法：把「收尾」抽成 ensureFinalized()，所有路徑（onFinish / onError /
  // HTTP stream 關閉）都走它，idempotent 不重複。權威訊號從「SDK 願意呼叫
  // onFinish」改成「HTTP response stream 真的關了」—— 後者是作業系統層面、
  // 可信。
  let finalized = false;
  let finalText = "";
  let finalFinishReason: string | undefined;
  const ensureFinalized = async (
    reason: "onFinish" | "onError" | "stream-close",
    opts?: { text?: string; error?: string; finishReason?: string },
  ): Promise<void> => {
    if (finalized) return;
    finalized = true;
    const text = opts?.text ?? finalText;
    recordRuntime("response-finished", {
      turnId,
      chars: text.length,
      firstChars: text.slice(0, 500),
      closeReason: reason,
      finishReason: opts?.finishReason ?? finalFinishReason ?? null,
      error: opts?.error ?? null,
    });
    if (!convoId) return;
    await finalizeInflight({
      conversationId: convoId,
      status: opts?.error ? "error" : "done",
      finalText: text,
      error: opts?.error,
    });
  };

  const result = streamText({
    model: pickModel(),
    system: systemPrompt,
    messages: await convertToModelMessages(messages),
    tools: duffyTools,
    // Slice β (2026-06-15): bumped 5 → 15 to enable continuous-action turns.
    // After Slice α opened Duffy Workspace as auto-execute sandbox, the 5-step
    // cap was the next bottleneck — Duffy could write freely but only ~2-3 ops
    // before being cut off. 15 lets him chain: read → read → write-sandbox →
    // observe → write-sandbox → propose-vault-edit → text, which is the
    // "Claude Code-like 來去自如" feel Yen asked for.
    // Token cost: each step is a tool call + maybe small text. 15 × ~1-3k =
    // ≤45k worst case per turn. Daily budget enforced separately by
    // trust-config.daily_token_budget.
    stopWhen: stepCountIs(15),
    // Smooth Kimi's coarse chunks into char-by-char output so Duffy's reply
    // types itself onto the screen instead of dumping in 2-3 big blocks.
    // Chinese has little whitespace so 'word' would still feel chunky —
    // regex `/./` emits per UTF-8 character (Chinese + English alike).
    // 8ms × character ≈ 125 chars/sec, brisk typing feel.
    experimental_transform: smoothStream({
      delayInMs: 8,
      chunking: /./,
    }),
    // Slice 7.7: as Kimi emits text deltas, mirror them into the inflight
    // store so we can recover the response if the client disconnects.
    onChunk({ chunk }) {
      if (!convoId) return;
      if (chunk.type === "text-delta") {
        void appendInflight(convoId, chunk.text);
      }
    },
    // Flight recorder — log every tool call so we can see if Duffy actually
    // calls get_current_time / propose_schedule / etc. or skips them.
    onStepFinish({ toolCalls, toolResults }) {
      for (const tc of toolCalls ?? []) {
        recordRuntime("tool-call", {
          turnId,
          tool: tc.toolName,
          input: tc.input,
        });
      }
      for (const tr of toolResults ?? []) {
        recordRuntime("tool-result", {
          turnId,
          tool: tr.toolName,
          // Truncate to avoid huge tape lines from search results etc.
          output:
            typeof tr.output === "string"
              ? tr.output.slice(0, 500)
              : JSON.stringify(tr.output).slice(0, 500),
        });
      }
    },
    // Slice 7.7: on natural completion, finalize the inflight entry with
    // the full text. Client will see this on next /api/chat/inflight read.
    //
    // Patch A/B (2026-06-14): finalize 移到 ensureFinalized() 做、idempotent；
    // 這裡只 cache text + finishReason，並負責 token usage 記帳。
    async onFinish({ text, usage, finishReason }) {
      finalText = text;
      finalFinishReason = finishReason;
      try {
        const { recordTokenUsage } = await import(
          "@/lib/agent/storage/token-usage"
        );
        await recordTokenUsage({
          call_site: "duffy-chat",
          model: modelLabel(),
          usage,
          ref: convoId,
        });
      } catch {
        /* swallow */
      }
      await ensureFinalized("onFinish", { text, finishReason });
    },
    onError({ error }) {
      const msg = error instanceof Error ? error.message : String(error);
      recordRuntime("error", { turnId, error: msg });
      console.error("[duffy] streamText error:", error);
      void ensureFinalized("onError", { error: msg });
    },
  });

  const httpResponse = result.toUIMessageStreamResponse({
    onError(error) {
      return error instanceof Error ? error.message : String(error);
    },
  });

  // Patch A — HTTP stream-close watchdog。
  // 包一層 ReadableStream、把 finally 當成「stream 真的關了」的權威訊號。
  // 不論 onFinish/onError 有沒有跑、stream 關了就強制走 ensureFinalized()。
  // idempotent 保證不會跟正常路徑打架。
  const upstream = httpResponse.body;
  if (!upstream) {
    await ensureFinalized("stream-close", {
      error: "no response body — streamText returned without stream",
    });
    return httpResponse;
  }
  const wrapped = new ReadableStream<Uint8Array>({
    async start(controller) {
      const reader = upstream.getReader();
      try {
        while (true) {
          const { done, value } = await reader.read();
          if (done) break;
          controller.enqueue(value);
        }
        controller.close();
      } catch (err) {
        controller.error(err);
      } finally {
        if (!finalized) {
          await ensureFinalized("stream-close", {
            error:
              "stream closed without onFinish/onError — likely SDK/model finish_reason mismatch",
          });
        }
      }
    },
  });

  return new Response(wrapped, {
    status: httpResponse.status,
    statusText: httpResponse.statusText,
    headers: httpResponse.headers,
  });
}
